MAIL FROM: ian.wright@well.ox.ac.uk
RCPT TO: alfresco-notifications+1543@localhost
DATA
Content-Type: multipart/mixed;boundary="------------16805641CC7205F287204436"

This is a multi-part message in MIME format.
--------------16805641CC7205F287204436
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit

Test attachment


--------------16805641CC7205F287204436
Content-Type: text/plain; charset=UTF-8;
 name="hello.txt"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
 filename="hello.txt"

aGVsbG8K
--------------16805641CC7205F287204436--
.


